SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
GROUND_HEIGHT = SCREEN_HEIGHT - 62

BG_MULTI_TIMES = SCREEN_HEIGHT / 224
BG_PLAYER_CURSOR_TIMES = 2.70
ENEMY_SPEED = 1.0

FONT = r'resources\font_mario.fon'

GRAVITY = 1.0
ANTI_GRAVITY = 0.3
